Aliaksandr sumich patch 1
angarsky/diveintopython pull request #10
Opened 2023-04-25 16:13 UTC by AliaksandrSumich

2023-04-26 06:22 UTC, AliaksandrSumich commented
Added functions.md and functions/generetors.md

2023-05-03 18:27 UTC, angarsky requested changes
1. Need to fix syntax, typo, markup mistakes.
2. Review the Keyword list and adjust the text by keywords. Let's consider that at least one keyword from each group should be used in text (in header is better).

2023-05-03 18:27 UTC, angarsky commented on learn/functions/recursion.md
> +Python recursive functions are functions that call themselves during execution to solve a problem by breaking it down into smaller sub-problems. Recursion in Python involves two main steps: defining
Add empty line.

2023-05-03 18:27 UTC, angarsky commented on learn/functions/recursion.md
> +### Tips and Best Practices for Python Recursive Programming
Add empty line.

2023-05-03 18:27 UTC, angarsky commented on learn/functions/recursion.md
> +### Common mistakes and pitfalls in Python Recursion
Add empty line.

2023-05-03 18:27 UTC, angarsky commented on learn/functions/recursion.md
> +1) Memoization: Memoization is the process of storing previously computed results to avoid repeated calculation. This can significantly reduce the runtime of a recursive function.
Use heading here instead of the list.

2023-05-03 18:27 UTC, angarsky commented on learn/functions/return a function.md
> +#### Example 1:
`Example 1:` is not a good heading.

2023-05-03 18:27 UTC, angarsky commented on learn/functions/return a function.md
> +#### Example 1:
+ Update the next heading as well

2023-05-03 18:27 UTC, angarsky commented on learn/functions/return a function.md
> +#### Example 1:
Add something after `:`.

2023-05-03 18:27 UTC, angarsky commented on learn/functions.md
We need the `function arguments` section in this file.

2023-05-03 18:27 UTC, angarsky commented on learn/functions.md
\+ ` function documentation` section about how to write descriptions/annotations for functions.

2023-05-03 18:27 UTC, angarsky commented on learn/functions.md
\+ ` function name` with rules how to name fucntions

2023-05-07 09:02 UTC, angarsky commented on learn/functions/generators.md
> +## Differences between generators and regular functions in python
Add empty lines before and after a heading.

2023-05-07 09:02 UTC, angarsky commented on learn/functions/generators.md
> +## Common use cases for generator functions
Add empty lines before a heading.

2023-05-07 09:33 UTC, angarsky requested changes
Much better! But the content still requires some fixes.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/generators.md
> +### Lazy Execution:
Let's remove ":" in the end of heading.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/generators.md
> +### Threading with Generators:
Remove ":" from the heading.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/global_variables.md
> +### Example 1: Accessing a global variable **inside** a function
Let's do not use bold in headings.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/global_variables.md
> +### Example 2: Accessing the global variable **outside** the function
Let's do not use bold in headings.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/global_variables.md
> +### Global variable example:
Remove ":" from the heading.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/global_variables.md
> +### Local Variable Example:
Remove ":" from the heading.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/global_variables.md
> +## The role of non-local variables in python
Python should start from an upper-case character.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/global_variables.md
> +### Program to count the number of times a function is called:
Remove ":" from the heading.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/global_variables.md
> +Function naming conventions in Python follow the same PEP 8 guidelines, using lowercase letters and underscores to separate words. Function names should also be descriptive and convey the purpose of
If we reference to some external documentation - it's good to insert an HTML link to the source. But add links only to the trusted official sources.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/global_variables.md
> +Function naming conventions in Python follow the same PEP 8 guidelines, using lowercase letters and underscores to separate words. Function names should also be descriptive and convey the purpose of
In this case I mean "PEP 8 guidelines".

2023-05-07 09:33 UTC, angarsky commented on learn/functions/import_functions.md
Too much "import" word in a bold wrapper in the beginning of a page. Please reduce an amount, keep 1 of them.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/import_functions.md
> +## The different ways to import functions in python
"python" should start from a upper-case character.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/import_functions.md
> +## Importing specific functions from a file in python
"python" should start from a upper-case character.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/import_functions.md
> +## Organizing your python code: how to create a custom module with importable functions
"python" should start from a upper-case character.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/import_functions.md
> +There are several ways to import functions in Python. One way is to define functions in a separate file and then import them into the main script using the `import function from file` syntax. Another
`**'map' function with multiple arguments**` - don't wrap code samples into bold.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/lambda.md
> +2. Use Lambda functions with **`map()`, `filter()`, and `reduce()`**: These higher-order functions require a function argument, and Lambda functions are a great way to create **simple functions on th
Remove bold wrapper around of code samples.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/nested.md
> +## Understanding python's nested functions
Python should start from the upper-case character.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/nested.md
> +### Two examples of nested functions in Python:
Remove ":" from the heading.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/nested.md
> +## Advantages of using nested functions in python
Python should start from the upper-case character.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/nested.md
> +## Creating nested functions in python
Python should start from the upper-case character.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/nested.md
Too much Nested Functions in the bold wrapper. Reduce the amount, keep 20-30%.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/nested.md
> +## Best practices for using nested functions in python
Python should start from the upper-case character.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/nested.md
> +## Common errors to avoid when using nested functions in python programming.
Python should start from the upper-case character.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/partial_functions.md
> +## Understanding python partial functions: a beginner's guide to function modification
Python should start from the upper-case character.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/partial_functions.md
Too much `**partial function**` in the bold wrapper. Reduce amount.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/partial_functions.md
> +## When to use partial functions vs. lambdas in python: key differences and similarities
Python from lower case.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/partial_functions.md
> +### Example of using a partial function:
Remove ":" from heading.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/partial_functions.md
> +### Example of using a lambda function:
Remove ":" from the heading.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/partial_functions.md
> +## How to create partial functions in python: a step-by-step tutorial
"python"

2023-05-07 09:33 UTC, angarsky commented on learn/functions/partial_functions.md
> +To create a partial function in Python, you need to follow the following steps:
Add empty line.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/partial_functions.md
> +## Enhancing code readability with partial functions in python: tips and tricks
"python"

2023-05-07 09:33 UTC, angarsky commented on learn/functions/recursion.md
> +**Recursive programming** is a technique in programming where a function **calls itself repeatedly** until it reaches a base or terminal case. It is a powerful tool when dealing with certain types of
`**recursive functions.**` bold wrapper shouldn't include the dot `.` of the sentence.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/recursion.md
> +Note that tail recursion optimization can only be applied to recursive functions that have a tail call, i.e., a recursive call that occurs at the end of the function's execution.
For note text we can use `> ` markup - https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-text

2023-05-07 09:33 UTC, angarsky commented on learn/functions/return_function.md
> +## Return function in Python
Add a text between H2 and H3 or we can remove this H2 and make further H3 => H2.

2023-05-07 09:33 UTC, angarsky commented on learn/functions/return_function.md
> +#### Example 2: Add or multiply
It's H4. I guess it's a typo mistake.

2023-05-08 09:25 UTC, angarsky requested changes
Markup is good now! 

Let's add to the text / headings next keywords (1-2 occurrences):

- what is a lambda function in python
- how to call a function
- what is a function in python
- how to write a function in python
- create a function in python
- return(s) multiple values (add 1-2 more to the text)
- call a function from another file

2023-05-09 10:53 UTC, angarsky approved these changes
🚀

2023-05-09 10:53 UTC, merged