Update import.md
angarsky/diveintopython pull request #28
Opened 2023-10-26 23:19 UTC by almargit

2023-10-27 12:22 UTC, angarsky requested changes
Thank you for your contribution! But some changes are requested.

2023-10-27 12:22 UTC, angarsky commented on learn/classes/import.md
> +The import [statement in Python](https://diveintopython.org/learn/statements) allows us to use external modules and [packages](https://diveintopython.org/learn/modules/packages) that provide addition
Remove new links.

2023-10-27 12:22 UTC, angarsky commented on learn/classes/import.md
> +Once we import the module, we can use its [functions](https://diveintopython.org/learn/functions) and attributes.
Remove new links.

2023-10-27 12:22 UTC, angarsky commented on learn/classes/import.md
> +## Importing All Classes from a Module Using From Command
Maybe "using the From Command"? Or "with the From Command".

2023-10-28 14:13 UTC, almargit commented
Thank you for your feedback. I have made some adjustments to the pull request in accordance with your notes, as well as a couple of minor changes. Please take a look.

2023-10-30 19:15 UTC, angarsky requested changes
Added new notes regarding the changes. Please, review them.

2023-10-30 19:15 UTC, angarsky commented on learn/classes/static_class.md
> +1. Utility Functions
Let's switch to H3 `###` headings + next ones as well.

2023-10-30 19:15 UTC, angarsky commented on learn/classes/import.md
> +1. Identify the Target Directory: First, you need to identify the directory from which you want to import classes. This directory should be in the parent directory of your current script.
Let's switch to H3 headings or highlight `Identify the Target Directory` text with bold. + Further items as well.

2023-10-30 19:15 UTC, angarsky commented on learn/classes/static_class.md
> +Now that you're familiar with class methods and static methods, it's time to delve into the world of static class python and its distinctive properties.
1. Python should start from upper-case.
2. "static class python" doesn't sound good. Let's rephrase it.

2023-10-31 09:18 UTC, angarsky approved these changes
Good job! Let's publish it.

2023-10-31 09:18 UTC, merged