Aliaksandr exceptions
angarsky/diveintopython pull request #61
Opened 2024-02-13 19:19 UTC by AliaksandrSumich

Added exceptions article

2024-02-13 23:35 UTC, angarsky requested changes

2024-02-13 23:35 UTC, angarsky commented on learn/exceptions.md
Let's re-group H2 and H3 headings. They look  a bit messy at the moment.

1. H2-H3 headings should be grouped by sense. H2 headings is a backbone of the article: a table of contents (that consists of H2 headings) must provide clear understanding about all sections of the article.

2. For H3 headings prior a code example section - write them as "Example: ...".

2024-02-13 23:35 UTC, angarsky commented on learn/exceptions.md
> +In Python programming, exceptions are an essential part of writing clean, robust, and efficient code. Exceptions are used for handling errors gracefully and managing the program flow when unexpected
"The `python exception` mechanism..."

I think we don't need highlight here the 'python' word.

2024-02-13 23:35 UTC, angarsky commented on learn/exceptions.md
> +### Printing and Throwing Exceptions
Two H3 headings go one by one.

2024-02-15 07:38 UTC, AliaksandrSumich commented
Corrected according to the comments. I took the H2 headings from the book (of course, I paraphrased them a little using Ghat GPT), so the structure of the article as a whole should be correct. If you have suggestions on how to improve the article, I will certainly follow them.

2024-02-15 12:54 UTC, merged